### ISSUE TITLE
Question, iOS compatibility

### ISSUE THREAD

**Issue by eblabs** [intelligide/assimpnet-unity#2]
Hi,
Just wanted to ask if this works with iOS.

Thanks!

Eric

**Comment by intelligide** [comment]
Probably, I never tested with ios. However it works with android.

**Comment by eblabs** [comment]
Ah I see there is a repo for a version of this thats already been compiled.
https://github.com/intelligide/assimp-unity

I gave this a try, but it looks like all of the plugin folders are empty. Is there something Im missing?

Thanks!!

**Comment by intelligide** [comment]
assimp-unity can only be installed via the Unity package manager. I described the installation in the docs (https://intelligide.github.io/assimp-unity/installation/). Docs are WIP , so use `https://intelligide.pkgs.visualstudio.com/0435f2bc-ce0a-4490-ac97-883fb250890d/_packaging/stable/npm/registry/` as registry url instead of the indicated one.

The git repo only store package files (like package.json and others stuffs). I created an Azure Pipeline that build AssimpNet (this repo) and Assimp libraries for each supported platforms (See https://github.com/intelligide/assimp-unity/blob/master/azure-pipelines.yml)

**Comment by eblabs** [comment]
Thanks, I was able to get it installed.

I wanted to give it a try, but didnt see any examples yet. Can you point me in the right direction or are there any code examples on how to load a file?
https://intelligide.github.io/assimp-unity/usage/

Thanks again!!

**Comment by intelligide** [comment]
Official AssimpNet project provide a [sample project](https://bitbucket.org/Starnick/assimpnet/src/1eef562da794e681ad7cd4b9f6f1d47766ae0ffa/AssimpNet.Sample/?at=release%2F4.1.0).

You can take a look at [this function](https://bitbucket.org/Starnick/assimpnet/src/1eef562da794e681ad7cd4b9f6f1d47766ae0ffa/AssimpNet.Sample/SimpleModel.cs?at=release%2F4.1.0#lines-68) and [this one](https://bitbucket.org/Starnick/assimpnet/src/1eef562da794e681ad7cd4b9f6f1d47766ae0ffa/AssimpNet.Sample/SimpleModel.cs?at=release%2F4.1.0#lines-143).

I updated the docs too with somes examples.

**Comment by eblabs** [comment]
Thanks for all the info, Im looking through these now. The updated docs are a big help!

Ah, one more question. Can these be imported as Unity objects, ie "GameObjects"? It looks like these are all special object types?

Thanks again!!

**Comment by intelligide** [comment]
No, they can't. But you can write your own algorithm for converting assimp meshes to Unity meshes with [Unity Mesh API](https://docs.unity3d.com/ScriptReference/Mesh.html). Materials are harder to import.

I may later add some scripts and other tools in the package. I plan to add importers once Unity implements importer override.

**Comment by eblabs** [comment]
Thanks again @intelligide, Im getting a better idea of how assimpnet was designed. I was thinking it was a bit more plug and play for unity.

I look foward to seeing your unity updates!

All the best,

Eric
